import assert from "node:assert/strict";
import test from "node:test";
import { RulateClient, sanitizeFormattedHtml } from "../dist/index.js";
const bookHtml=`<article><h1>Русское название</h1><div style="font-size:14px">Original title</div><div id="Info"><div class="slick"><img src="/i/book/1.jpg" alt="Poster"></div><p><strong>Автор:</strong><a href="/search?from=book&t=Author">Author</a></p><p><strong>Выпуск:</strong><em>продолжается</em></p><p><strong>Жанры:</strong><a href="/search?genres%5B0%5D=37">фэнтези</a></p><p><strong>Тэги:</strong><a href="/search?tags%5B0%5D=1">система</a></p><span class="rating-info">82.5% (2)</span><span class="rating-info">100% (3)</span><div id="liker"><span>1</span><span>207</span></div></div><div class="book-description"><p>Описание <strong>с форматированием</strong>.</p></div><tr id='c_25027713' data-id='25027713' class='chapter_row'><td class='t'><a href='/book/201009/25027713/ready_new'>Глава 1</a></td><td><time datetime='2026-06-27T23:41:36+03:00'>date</time></td><td><a href='/book/201009/25027713/ready_new' class='btn btn-info'>читать</a></td></tr><dt>Состояние перевода:</dt><dd><span>В работе</span></dd><dt>Просмотров:</dt><dd>933</dd></article>`;
const membersHtml=`<table id="people"><tr><td>1</td><td><a href="/users/322523">translator</a> (создатель)</td><td>Модератор</td></tr></table>`;
const catalogHtml=`<div class="pagination books-pagination"><a href="/search/index/Book_page/12">12</a></div><ul class='search-results'><li><div class='th'><img src='/i/book/1.jpg'></div><p class='book-tooltip'><a href='/book/201009'>Русское название</a><br><small>Original title</small></p><div class='meta'>Перевод от <a href='/users/322523'>translator</a><span class="label" rel="tooltip" title="Кол-во глав всего / Кол-во платных глав">207 / 150</span><span class="label" rel="tooltip" title="Рейтинг">4.5 / 14</span><span class="label" rel="tooltip" title="Качество перевода">4.9 / 13</span><span class="label" rel="tooltip" title="Лайки">99</span><p class="book-descr-full">Полное описание</p><p><a href="/search?genres%5B0%5D=37">фэнтези</a><a href="/search?tags%5B0%5D=1">система</a></p></div></li></ul>`;
const rawChapter=`<p style="text-align:center;color:red" data-x="1">Hello <strong>World</strong></p><img data-src="/i/chapter.jpg" onclick="evil()" alt="Art"><script>evil()</script>`;
const payload=JSON.stringify({id:25027713,title:"Глава 1",can_read:true,content:`<ul class="pager"><li>nav</li></ul><div class="content-text">${rawChapter}</div><p>https://tl.rulate.ru/book/201009</p>`});
function makeFetch(){const counts=new Map();const fetch=async(input,init={})=>{const url=String(input);counts.set(url,(counts.get(url)??0)+1);let body;if(url.includes('/readyajax')){assert.equal(new Headers(init.headers).get('x-requested-with'),'XMLHttpRequest');body=payload;}else if(url.endsWith('/members'))body=membersHtml;else if(url.includes('/search'))body=catalogHtml;else if(url.endsWith('/book/201009'))body=bookHtml;else return new Response('not found',{status:404});return new Response(body,{status:200});};return{fetch,counts};}
test('formatted HTML keeps semantics and removes executable markup',()=>{assert.equal(sanitizeFormattedHtml(rawChapter,'https://tl.rulate.ru/book/201009/1/ready_new'),'<p style="text-align:center">Hello <strong>World</strong></p><img src="https://tl.rulate.ru/i/chapter.jpg" alt="Art" loading="lazy">');});
test('catalog, book and chapter retain raw and formatted content',async()=>{const{fetch}=makeFetch();const client=new RulateClient({fetch,minRequestIntervalMs:0});const catalog=await client.getCatalog();assert.equal(catalog.totalPages,12);assert.equal(catalog.items[0]?.chapters.total,207);const book=await client.getBook(201009);assert.equal(book.poster?.url,'https://tl.rulate.ru/i/book/1.jpg');assert.equal(book.translators[0]?.name,'translator');const chapter=await client.getChapter(201009,book.chapters[0]);assert.equal(chapter.rawHtml,rawChapter);assert.equal(chapter.text,'Hello World\nArt');assert.equal(chapter.images[0]?.url,'https://tl.rulate.ru/i/chapter.jpg');});
test('identical concurrent requests are coalesced',async()=>{const{fetch,counts}=makeFetch();const client=new RulateClient({fetch,minRequestIntervalMs:0});await Promise.all([client.getBookTranslators(201009),client.getBookTranslators(201009),client.getBookTranslators(201009)]);assert.equal(counts.get('https://tl.rulate.ru/book/201009/members'),1);});
