import { absoluteUrl, attr, collectImages, decodeEntities, extractLinks, findAllElementsByClass, findAllElementsByTag, findElementByClass, findElementById, htmlToText, parseInteger, parsePeople, parseRating, sanitizeFormattedHtml, stripTags, uniquePeople, uniqueStrings } from "./html.js";
import { ContentUnavailableError, HttpTransport } from "./transport.js";
import type { BatchOptions, BatchResult, CatalogBook, CatalogPage, CatalogQuery, ChapterContent, ChapterDescriptor, ChapterOptions, ClientOptions, ImageAsset, Person, RequestOptions, RulateBook } from "./types.js";

export class RulateClient {
  private readonly transport: HttpTransport; private readonly baseUrl: string;
  public constructor(options: ClientOptions = {}) { this.transport = new HttpTransport(options); this.baseUrl = (options.baseUrl ?? "https://tl.rulate.ru").replace(/\/+$/, ""); }
  public async getCatalog(query: CatalogQuery = {}): Promise<CatalogPage> {
    const page = Math.max(1, Math.trunc(query.page ?? 1)); const path = page === 1 ? "/search" : `/search/index/Book_page/${page}`; const url = new URL(path, `${this.baseUrl}/`);
    if (query.text) url.searchParams.set("t", query.text); if (query.sort) url.searchParams.set("sort", query.sort); if (query.category !== undefined) url.searchParams.set("cat", String(query.category));
    appendIndexed(url.searchParams, "genres", query.genres); appendIndexed(url.searchParams, "tags", query.tags); appendIndexed(url.searchParams, "fandoms", query.fandoms);
    const requestOptions: { signal?: AbortSignal; refresh?: boolean } = {}; if (query.signal) requestOptions.signal = query.signal; if (query.refresh !== undefined) requestOptions.refresh = query.refresh;
    return parseCatalogPage(await this.transport.getMetadata(url.toString(), requestOptions), url.toString(), page);
  }
  public async *iterateCatalog(query: Omit<CatalogQuery,"page"> = {}): AsyncGenerator<CatalogPage,void,void> { let page=1; while(true){const result=await this.getCatalog({...query,page});yield result;if(!result.hasNextPage)return;page+=1;} }
  public searchBooks(text:string,query:Omit<CatalogQuery,"text">={}):Promise<CatalogPage>{return this.getCatalog({...query,text});}
  public async getBook(input:number|string,options:RequestOptions={}):Promise<RulateBook>{const bookId=parseBookId(input);const sourceUrl=`${this.baseUrl}/book/${bookId}`;const[rawPageHtml,translators]=await Promise.all([this.transport.getMetadata(sourceUrl,options),this.getBookTranslators(bookId,options).catch(()=>[] as Person[])]);return parseBookPage(rawPageHtml,sourceUrl,bookId,translators);}
  public async getBookTranslators(input:number|string,options:RequestOptions={}):Promise<Person[]>{const bookId=parseBookId(input);const url=`${this.baseUrl}/book/${bookId}/members`;const html=await this.transport.getMetadata(url,options);const people=parsePeople(html,url,"project");for(const row of findAllElementsByTag(html,"tr")){const role=stripTags(row.innerHtml.match(/<td[^>]*>[\s\S]*?<\/td>\s*<td[^>]*>[\s\S]*?<\/td>\s*<td[^>]*>([\s\S]*?)<\/td>/i)?.[1]??"")||null;for(const person of parsePeople(row.outerHtml,url,"project")){if(role)person.role=role;people.push(person);}}return uniquePeople(people);}
  public async getBookChapters(input:number|string,options:RequestOptions={}):Promise<ChapterDescriptor[]>{return(await this.getBook(input,options)).chapters;}
  public async getChapter(book:number|string,chapter:number|string|ChapterDescriptor,options:ChapterOptions={}):Promise<ChapterContent>{const bookId=parseBookId(book);const descriptor=typeof chapter==="object"?chapter:descriptorFromInput(bookId,chapter,this.baseUrl);if(descriptor.bookId!==bookId)throw new Error(`Chapter ${descriptor.id} belongs to book ${descriptor.bookId}, not ${bookId}.`);
    const translatorsPromise=options.includeTranslators===false?Promise.resolve([] as Person[]):this.getBookTranslators(bookId,options).catch(()=>[] as Person[]);const pagePromise=options.includePageHtml?this.transport.getChapter(descriptor.url,options).catch(()=>null):Promise.resolve(null);
    const rawResponse=await this.transport.getJsonish(descriptor.xhrUrl,{...options,chapter:true,headers:{"X-Requested-With":"XMLHttpRequest",Referer:descriptor.url,Accept:"application/json,text/javascript,*/*;q=0.8"}});const record=asRecord(rawResponse);if(record.can_read===false)throw new ContentUnavailableError(`Chapter ${descriptor.id} is not readable with the supplied session.`,descriptor.url);
    const wrapper=typeof record.content==="string"?record.content:"";const rawHtml=findElementByClass(wrapper,"content-text")?.innerHtml??inferRawChapterHtml(wrapper);if(!rawHtml.trim())throw new ContentUnavailableError(`Chapter ${descriptor.id} returned no readable content.`,descriptor.url);const formattedHtml=sanitizeFormattedHtml(rawHtml,descriptor.url);
    const[projectPeople,pageHtml]=await Promise.all([translatorsPromise,pagePromise]);const translators=uniquePeople([...parsePeople(wrapper,descriptor.url,"chapter"),...(pageHtml?parsePeople(pageHtml,descriptor.url,"chapter"):[]),...projectPeople]);
    return{id:typeof record.id==="number"?Math.trunc(record.id):descriptor.id,bookId,title:typeof record.title==="string"&&record.title.trim()?decodeEntities(record.title.trim()):descriptor.title,sourceUrl:descriptor.url,xhrUrl:descriptor.xhrUrl,publishedAt:descriptor.publishedAt,translators,images:collectImages(rawHtml,descriptor.url,"illustration"),rawHtml,formattedHtml,text:htmlToText(formattedHtml),pageHtml,rawResponse,fetchedAt:new Date().toISOString()};}
  public async getChapterRawHtml(book:number|string,chapter:number|string|ChapterDescriptor,options:ChapterOptions={}):Promise<string>{return(await this.getChapter(book,chapter,options)).rawHtml;}
  public async getChapterFormattedHtml(book:number|string,chapter:number|string|ChapterDescriptor,options:ChapterOptions={}):Promise<string>{return(await this.getChapter(book,chapter,options)).formattedHtml;}
  public async getChapterPageHtml(book:number|string,chapter:number|string|ChapterDescriptor,options:RequestOptions={}):Promise<string>{const bookId=parseBookId(book);const descriptor=typeof chapter==="object"?chapter:descriptorFromInput(bookId,chapter,this.baseUrl);return this.transport.getChapter(descriptor.url,options);}
  public async getChapterTranslators(book:number|string,chapter:number|string|ChapterDescriptor,options:ChapterOptions={}):Promise<Person[]>{return(await this.getChapter(book,chapter,{...options,includeTranslators:true})).translators;}
  public async getPoster(input:number|string,options:RequestOptions={}):Promise<ImageAsset|null>{return(await this.getBook(input,options)).poster;}
  public async getBookImages(input:number|string,options:RequestOptions={}):Promise<ImageAsset[]>{return(await this.getBook(input,options)).images;}
  public async getChapters(book:number|string,chapters:readonly ChapterDescriptor[],options:BatchOptions={}):Promise<BatchResult[]>{const concurrency=Math.max(1,Math.trunc(options.concurrency??12));const output=new Array<BatchResult>(chapters.length);let cursor=0;const worker=async():Promise<void>=>{while(true){const index=cursor++;const descriptor=chapters[index];if(!descriptor)return;try{output[index]={descriptor,chapter:await this.getChapter(book,descriptor,options),error:null};}catch(error){const normalized=error instanceof Error?error:new Error(String(error));output[index]={descriptor,chapter:null,error:normalized};if(!options.continueOnError)throw normalized;}}};await Promise.all(Array.from({length:Math.min(concurrency,chapters.length)},()=>worker()));return output;}
  public async *streamChapters(book:number|string,chapters:readonly ChapterDescriptor[],options:BatchOptions={}):AsyncGenerator<BatchResult,void,void>{const concurrency=Math.max(1,Math.trunc(options.concurrency??12));let cursor=0;const active=new Map<number,Promise<{index:number;result:BatchResult}>>();const launch=(index:number):void=>{const descriptor=chapters[index];if(!descriptor)return;active.set(index,this.getChapter(book,descriptor,options).then((chapter)=>({index,result:{descriptor,chapter,error:null}})).catch((error:unknown)=>({index,result:{descriptor,chapter:null,error:error instanceof Error?error:new Error(String(error))}})));};while(cursor<chapters.length&&active.size<concurrency)launch(cursor++);while(active.size){const settled=await Promise.race(active.values());active.delete(settled.index);if(settled.result.error&&!options.continueOnError)throw settled.result.error;yield settled.result;if(cursor<chapters.length)launch(cursor++);}}
  public clearCache():void{this.transport.clearCache();} public close():void{this.transport.close();}
}

function parseCatalogPage(rawHtml:string,sourceUrl:string,page:number):CatalogPage{const scope=findElementByClass(rawHtml,"search-results")?.innerHtml??rawHtml;const items=findAllElementsByTag(scope,"li").map((f)=>parseCatalogItem(f.outerHtml,sourceUrl)).filter((v):v is CatalogBook=>v!==null);const pages=[...rawHtml.matchAll(/Book_page\/(\d+)/g)].map((m)=>Number(m[1])).filter(Number.isFinite);const totalPages=pages.length?Math.max(page,...pages):null;return{page,totalPages,hasNextPage:totalPages!==null?page<totalPages:items.length>0&&/class=["'][^"']*next(?![^"']*disabled)/i.test(rawHtml),items,sourceUrl,rawHtml,fetchedAt:new Date().toISOString()};}
function parseCatalogItem(rawHtml:string,sourceUrl:string):CatalogBook|null{const bookLink=extractLinks(rawHtml,sourceUrl,(url)=>/^\/book\/\d+\/?$/.test(url.pathname))[0];if(!bookLink)return null;const id=Number(/\/book\/(\d+)/.exec(new URL(bookLink.url).pathname)?.[1]);if(!Number.isFinite(id))return null;const originalTitle=stripTags(/<small[^>]*>([\s\S]*?)<\/small>/i.exec(rawHtml)?.[1]??"")||null;const description=stripTags(findElementByClass(rawHtml,"book-descr-full")?.innerHtml??findElementByClass(rawHtml,"book-descr-short")?.innerHtml??"")||null;const poster=collectImages(rawHtml,sourceUrl,"poster").find((i)=>/\/i\/book\//.test(new URL(i.url).pathname))??null;const translator=parsePeople(/Перевод\s+от\s*([\s\S]{0,500})/i.exec(rawHtml)?.[1]??"",sourceUrl,"catalog")[0]??null;const labels=parseLabeledMetrics(rawHtml);const pair=/(\d[\d\s]*)\s*\/\s*(\d[\d\s]*)/.exec(labels.get("Кол-во глав всего / Кол-во платных глав")??"");const plain=stripTags(rawHtml);return{id,url:bookLink.url,title:bookLink.text,originalTitle,description,poster,translator,genres:linksByQueryKey(rawHtml,sourceUrl,"genres"),tags:linksByQueryKey(rawHtml,sourceUrl,"tags"),status:/состояние перевода:\s*([^<\n]+)/i.exec(plain)?.[1]?.trim()??null,lastActivityAt:/последняя активность:\s*([^<\n]+)/i.exec(plain)?.[1]?.trim()??null,chapters:{total:parseInteger(pair?.[1]),paid:parseInteger(pair?.[2])},rating:parseRating(labels.get("Рейтинг")),translationRating:parseRating(labels.get("Качество перевода")),likes:parseInteger(labels.get("Лайки")),rawHtml};}
function parseBookPage(rawPageHtml:string,sourceUrl:string,bookId:number,projectTranslators:Person[]):RulateBook{const title=stripTags(/<h1[^>]*>([\s\S]*?)<\/h1>/i.exec(rawPageHtml)?.[1]??"")||`Book ${bookId}`;const h1End=rawPageHtml.search(/<\/h1>/i);const originalTitle=stripTags(/<div[^>]*>([\s\S]*?)<\/div>/i.exec(h1End>=0?rawPageHtml.slice(h1End+5,h1End+2000):"")?.[1]??"")||null;const info=findElementById(rawPageHtml,"Info")?.innerHtml??rawPageHtml;const descriptionRaw=findElementByClass(rawPageHtml,"book-description")?.innerHtml??"";const formatted=sanitizeFormattedHtml(descriptionRaw,sourceUrl);const bookImages=collectImages(info,sourceUrl,"cover").filter((i)=>/\/i\/book\//.test(new URL(i.url).pathname));const poster=bookImages[0]?{...bookImages[0],type:"poster" as const}:null;const inline:Person[]=[];for(const match of info.matchAll(/(?:Перевод\s+от|владелец:)\s*([\s\S]{0,700})/gi))inline.push(...parsePeople(match[1]??"",sourceUrl,"project"));const ratings=[...info.matchAll(/<span[^>]+class=["'][^"']*rating-info[^"']*["'][^>]*>([\s\S]*?)<\/span>/gi)].map((m)=>stripTags(m[1]??""));const numbers=[...stripTags(findElementById(info,"liker")?.innerHtml??"").matchAll(/\d[\d\s]*/g)].map((m)=>parseInteger(m[0])).filter((v):v is number=>v!==null);const chapters=parseChapterRows(rawPageHtml,sourceUrl,bookId);const plain=stripTags(rawPageHtml);return{id:bookId,url:sourceUrl,title,originalTitle,description:{rawHtml:descriptionRaw,formattedHtml:formatted,text:htmlToText(formatted)},poster,images:uniqueImages(bookImages),authors:parseAuthors(info,sourceUrl),translators:uniquePeople([...inline,...projectTranslators]),genres:linksByQueryKey(info,sourceUrl,"genres"),tags:linksByQueryKey(info,sourceUrl,"tags"),fandoms:linksByQueryKey(info,sourceUrl,"fandoms"),status:fieldText(info,"Выпуск"),translationStatus:/Состояние перевода:\s*([^\n]+)/i.exec(plain)?.[1]?.trim()??null,rating:parseRating(ratings[0]),translationRating:parseRating(ratings[1]),likes:numbers[0]??null,thanks:numbers[1]??null,views:parseInteger(/Просмотров:\s*([\d\s]+)/i.exec(plain)?.[1]),chapters,chapterStats:{total:chapters.length,paid:chapters.some((c)=>c.paid)?chapters.filter((c)=>c.paid).length:null},rawPageHtml,fetchedAt:new Date().toISOString()};}
function parseChapterRows(html:string,sourceUrl:string,bookId:number):ChapterDescriptor[]{const out:ChapterDescriptor[]=[];for(const row of findAllElementsByClass(html,"chapter_row")){const id=parseInteger(attr(row.openTag,"data-id")??attr(row.openTag,"id")?.replace(/^c_/,""));if(id===null)continue;const links=extractLinks(row.innerHtml,sourceUrl,(url)=>new RegExp(`^/book/${bookId}/${id}/`).test(url.pathname));const read=links.find((l)=>/\/ready(?:_new)?\/?$/.test(new URL(l.url).pathname))??links[0];if(!read)continue;const timeTag=/<time\b[^>]*>/i.exec(row.innerHtml)?.[0]??"";out.push({id,bookId,title:read.text||`Chapter ${id}`,number:parseChapterNumber(read.text),url:read.url,xhrUrl:chapterXhrUrl(read.url),publishedAt:attr(timeTag,"datetime"),paid:/(?:платн|купить|RC|has-paid|paid)/i.test(row.innerHtml)?true:null,available:/btn-info|читать|готовый перевод/i.test(row.innerHtml),rawHtml:row.outerHtml});}return out;}
function descriptorFromInput(bookId:number,chapter:number|string,baseUrl:string):ChapterDescriptor{const id=parseChapterId(chapter);const url=`${baseUrl}/book/${bookId}/${id}/ready_new`;return{id,bookId,title:`Chapter ${id}`,number:null,url,xhrUrl:chapterXhrUrl(url),publishedAt:null,paid:null,available:true,rawHtml:""};}
function chapterXhrUrl(readUrl:string):string{const url=new URL(readUrl);url.pathname=url.pathname.replace(/_new\/?$/,"").replace(/\/$/,"")+"ajax";url.searchParams.set("is_new","true");return url.toString();}
function inferRawChapterHtml(wrapper:string):string{const marker=wrapper.match(/<p>https?:\/\/tl\.rulate\.ru\/book\/[\s\S]*?<\/p>/i);return marker?.index!==undefined?wrapper.slice(0,marker.index):wrapper;}
function parseAuthors(html:string,sourceUrl:string):Person[]{const out:Person[]=[];for(const match of html.matchAll(/<strong>\s*Автор:\s*<\/strong>([\s\S]{0,1500}?)(?:<\/p>|<p\b)/gi))for(const link of extractLinks(match[1]??"",sourceUrl))out.push({id:null,name:link.text,url:link.url,role:"Автор",scope:"project"});return uniquePeople(out);}
function linksByQueryKey(html:string,sourceUrl:string,key:string):string[]{return uniqueStrings(extractLinks(html,sourceUrl,(url)=>url.searchParams.has(`${key}[0]`)||url.search.includes(`${key}%5B`)).map((l)=>l.text));}
function fieldText(html:string,label:string):string|null{return stripTags(new RegExp(`<strong>\\s*${escapeForRegex(label)}:\\s*<\\/strong>([\\s\\S]{0,800}?)(?:<\\/p>|<p\\b)`,`i`).exec(html)?.[1]??"")||null;}
function parseLabeledMetrics(html:string):Map<string,string>{const out=new Map<string,string>();for(const match of html.matchAll(/<span[^>]+class=["'][^"']*label[^"']*["'][^>]+(?:rel=["']tooltip["'][^>]*)?title=["']([^"']+)["'][^>]*>([\s\S]*?)<\/span>/gi))out.set(decodeEntities(match[1]??"").trim(),stripTags(match[2]??""));return out;}
function parseBookId(input:number|string):number{if(typeof input==="number"&&Number.isInteger(input)&&input>0)return input;const id=Number(/(?:\/book\/)?(\d+)/.exec(String(input))?.[1]);if(!Number.isInteger(id)||id<=0)throw new Error(`Cannot parse Rulate book ID from: ${String(input)}`);return id;}
function parseChapterId(input:number|string):number{if(typeof input==="number"&&Number.isInteger(input)&&input>0)return input;const id=Number(/(?:\/book\/\d+\/)?(\d+)/.exec(String(input))?.[1]);if(!Number.isInteger(id)||id<=0)throw new Error(`Cannot parse Rulate chapter ID from: ${String(input)}`);return id;}
function parseChapterNumber(value:string):string|null{return/(?:глава|chapter)\s*([\d]+(?:[.,][\d]+)?)/i.exec(value)?.[1]?.replace(",",".")??null;}
function uniqueImages(images:ImageAsset[]):ImageAsset[]{const out:ImageAsset[]=[];const seen=new Set<string>();for(const image of images){if(seen.has(image.url))continue;seen.add(image.url);out.push(image);}return out;}
function appendIndexed(params:URLSearchParams,key:string,values?:number[]):void{values?.forEach((value,index)=>params.append(`${key}[${index}]`,String(value)));}
function asRecord(value:unknown):Record<string,unknown>{return value!==null&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}
function escapeForRegex(value:string):string{return value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");}
