import type { ImageAsset, Person, RatingValue } from "./types.js";
export interface HtmlFragment { tag: string; start: number; end: number; innerStart: number; innerEnd: number; openTag: string; outerHtml: string; innerHtml: string; }
const VOID_TAGS = new Set(["area","base","br","col","embed","hr","img","input","link","meta","param","source","track","wbr"]);
const ALLOWED_TAGS = new Set(["p","br","hr","strong","b","em","i","u","s","a","img","figure","figcaption","ul","ol","li","blockquote","pre","code","h1","h2","h3","h4","h5","h6","table","thead","tbody","tfoot","tr","th","td","sup","sub","ruby","rt","rp"]);
const BLOCK_TAGS = /<\/?(?:p|div|li|blockquote|pre|h[1-6]|tr|table|ul|ol|figure|figcaption)\b[^>]*>|<(?:br|hr)\b[^>]*>/gi;
export function decodeEntities(value: string): string { const named: Record<string,string>={amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:" ",laquo:"«",raquo:"»",ndash:"–",mdash:"—",hellip:"…"}; return value.replace(/&(#x?[0-9a-f]+|[a-z][a-z0-9]+);/gi,(match,entity:string)=>{ if(/^#x/i.test(entity)){const code=Number.parseInt(entity.slice(2),16);return Number.isFinite(code)?String.fromCodePoint(code):match;} if(entity.startsWith("#")){const code=Number.parseInt(entity.slice(1),10);return Number.isFinite(code)?String.fromCodePoint(code):match;} return named[entity.toLowerCase()]??match;}); }
export function stripTags(value:string):string{return decodeEntities(value.replace(/<script\b[^>]*>[\s\S]*?<\/script\s*>/gi,"").replace(/<style\b[^>]*>[\s\S]*?<\/style\s*>/gi,"").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim();}
export function htmlToText(value:string):string{return decodeEntities(value.replace(/<img\b[^>]*\balt=(?:"([^"]*)"|'([^']*)')[^>]*>/gi,(_m,a,b)=>` ${a??b??""} `).replace(BLOCK_TAGS,"\n").replace(/<[^>]+>/g,"")).replace(/\r\n?/g,"\n").replace(/[\t ]+\n/g,"\n").replace(/\n[\t ]+/g,"\n").replace(/[\t ]{2,}/g," ").replace(/\n{3,}/g,"\n\n").trim();}
export function absoluteUrl(value:string|null|undefined,baseUrl:string):string|null{if(!value)return null;const decoded=decodeEntities(value.trim());if(!decoded||/^(?:javascript|data):/i.test(decoded))return null;try{const url=new URL(decoded,baseUrl);return["http:","https:"].includes(url.protocol)?url.toString():null;}catch{return null;}}
export function attributes(rawTag:string):Map<string,string>{const output=new Map<string,string>();for(const match of rawTag.matchAll(/([:\w-]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+)))?/g)){const name=(match[1]??"").toLowerCase();if(!name||name.startsWith("<"))continue;output.set(name,match[2]??match[3]??match[4]??"");}return output;}
export function attr(rawTag:string,name:string):string|null{return attributes(rawTag).get(name.toLowerCase())??null;}
export function hasClass(rawTag:string,className:string):boolean{return(attr(rawTag,"class")??"").split(/\s+/).includes(className);}
export function findElementById(html:string,id:string,from=0):HtmlFragment|null{return findElement(html,(tag)=>attr(tag,"id")===id,from);}
export function findElementByClass(html:string,className:string,from=0):HtmlFragment|null{return findElement(html,(tag)=>hasClass(tag,className),from);}
export function findAllElementsByClass(html:string,className:string):HtmlFragment[]{const out:HtmlFragment[]=[];let cursor=0;while(cursor<html.length){const f=findElementByClass(html,className,cursor);if(!f)break;out.push(f);cursor=Math.max(f.end,f.start+1);}return out;}
export function findAllElementsByTag(html:string,tagName:string):HtmlFragment[]{const out:HtmlFragment[]=[];const wanted=tagName.toLowerCase();let cursor=0;while(cursor<html.length){const f=findElement(html,(_raw,tag)=>tag.toLowerCase()===wanted,cursor);if(!f)break;out.push(f);cursor=Math.max(f.end,f.start+1);}return out;}
function findElement(html:string,predicate:(rawOpenTag:string,tagName:string)=>boolean,from=0):HtmlFragment|null{const pattern=/<([a-zA-Z][\w:-]*)\b[^>]*>/g;pattern.lastIndex=from;for(let m=pattern.exec(html);m;m=pattern.exec(html)){const openTag=m[0];const tag=(m[1]??"").toLowerCase();if(openTag.startsWith("</")||!predicate(openTag,tag))continue;const start=m.index;const innerStart=start+openTag.length;if(VOID_TAGS.has(tag)||/\/\s*>$/.test(openTag))return{tag,start,end:innerStart,innerStart,innerEnd:innerStart,openTag,outerHtml:openTag,innerHtml:""};const closing=findClosingTag(html,tag,innerStart);if(!closing)return{tag,start,end:html.length,innerStart,innerEnd:html.length,openTag,outerHtml:html.slice(start),innerHtml:html.slice(innerStart)};return{tag,start,end:closing.end,innerStart,innerEnd:closing.start,openTag,outerHtml:html.slice(start,closing.end),innerHtml:html.slice(innerStart,closing.start)};}return null;}
function findClosingTag(html:string,tag:string,from:number):{start:number;end:number}|null{const pattern=new RegExp(`<\\/?${escapeRegExp(tag)}\\b[^>]*>`,`gi`);pattern.lastIndex=from;let depth=1;for(let m=pattern.exec(html);m;m=pattern.exec(html)){const token=m[0];if(/^<\s*\//.test(token)){depth-=1;if(depth===0)return{start:m.index,end:m.index+token.length};}else if(!/\/\s*>$/.test(token))depth+=1;}return null;}
export function sanitizeFormattedHtml(input:string,sourceUrl:string):string{const cleaned=input.replace(/<script\b[^>]*>[\s\S]*?<\/script\s*>/gi,"").replace(/<style\b[^>]*>[\s\S]*?<\/style\s*>/gi,"").replace(/<iframe\b[^>]*>[\s\S]*?<\/iframe\s*>/gi,"").replace(/<form\b[^>]*>[\s\S]*?<\/form\s*>/gi,"").replace(/<!--([\s\S]*?)-->/g,"");const tokens=cleaned.match(/<[^>]*>|[^<]+/g)??[];const output:string[]=[];for(const token of tokens){if(!token.startsWith("<")){output.push(token);continue;}const parsed=/^<\s*(\/?)\s*([a-zA-Z0-9:-]+)([\s\S]*?)\/?\s*>$/.exec(token);if(!parsed)continue;const closing=parsed[1]==="/";const tag=(parsed[2]??"").toLowerCase();if(["div","section","article","span"].includes(tag)){if(closing&&tag==="div")output.push("\n");continue;}if(!ALLOWED_TAGS.has(tag))continue;if(closing){if(!VOID_TAGS.has(tag))output.push(`</${tag}>`);continue;}const map=attributes(token);const safe:string[]=[];if(tag==="a"){const href=absoluteUrl(map.get("href"),sourceUrl);if(href)safe.push(`href="${escapeAttribute(href)}"`,'rel="noopener noreferrer"');}else if(tag==="img"){const source=["src","data-src","data-lazy-src","data-original"].map((n)=>map.get(n)).find(Boolean)??firstSrcset(map.get("srcset"));const src=absoluteUrl(source,sourceUrl);if(!src)continue;safe.push(`src="${escapeAttribute(src)}"`,`alt="${escapeAttribute(map.get("alt")??"")}"`);const title=map.get("title");if(title)safe.push(`title="${escapeAttribute(title)}"`);safe.push('loading="lazy"');}else if(tag==="ol"){const start=map.get("start");if(start&&/^\d+$/.test(start))safe.push(`start="${start}"`);}else if(tag==="td"||tag==="th"){for(const name of["colspan","rowspan"]){const value=map.get(name);if(value&&/^\d+$/.test(value))safe.push(`${name}="${value}"`);}}if(["p","h1","h2","h3","h4","h5","h6","td","th"].includes(tag)){const style=map.get("style")??"";const alignment=/text-align\s*:\s*(left|right|center|justify)/i.exec(style)?.[1]?.toLowerCase();if(alignment)safe.push(`style="text-align:${alignment}"`);}output.push(`<${tag}${safe.length?` ${safe.join(" ")}`:""}>`);}return output.join("").replace(/\n{3,}/g,"\n\n").trim();}
export function collectImages(html:string,sourceUrl:string,type:ImageAsset["type"]="illustration"):ImageAsset[]{const out:ImageAsset[]=[];const seen=new Set<string>();for(const match of html.matchAll(/<img\b[^>]*>/gi)){const tag=match[0];const map=attributes(tag);const candidates:Array<[ImageAsset["sourceAttribute"],string|undefined]>=[["src",map.get("src")],["data-src",map.get("data-src")],["data-lazy-src",map.get("data-lazy-src")],["data-original",map.get("data-original")],["srcset",firstSrcset(map.get("srcset"))??undefined]];const candidate=candidates.find(([,v])=>Boolean(v));if(!candidate)continue;const url=absoluteUrl(candidate[1],sourceUrl);if(!url||seen.has(url))continue;seen.add(url);out.push({url,type,alt:map.get("alt")?decodeEntities(map.get("alt")??""):null,title:map.get("title")?decodeEntities(map.get("title")??""):null,sourceAttribute:candidate[0]});}return out;}
export function extractLinks(html:string,sourceUrl:string,predicate?:(url:URL,text:string)=>boolean):Array<{url:string;text:string;tag:string}>{const out=[] as Array<{url:string;text:string;tag:string}>;for(const match of html.matchAll(/<a\b[^>]*href=(?:"([^"]*)"|'([^']*)'|([^\s>]+))[^>]*>([\s\S]*?)<\/a\s*>/gi)){const href=match[1]??match[2]??match[3]??"";const text=stripTags(match[4]??"");const absolute=absoluteUrl(href,sourceUrl);if(!absolute)continue;const url=new URL(absolute);if(predicate&&!predicate(url,text))continue;out.push({url:absolute,text,tag:match[0]});}return out;}
export function parsePeople(html:string,sourceUrl:string,scope:Person["scope"]):Person[]{const out:Person[]=[];const seen=new Set<string>();for(const link of extractLinks(html,sourceUrl,(url)=>/^\/users\/\d+\/?$/.test(url.pathname))){const id=Number(/\/users\/(\d+)/.exec(new URL(link.url).pathname)?.[1]);const key=`${Number.isFinite(id)?id:""}:${link.text.toLowerCase()}`;if(!link.text||seen.has(key))continue;seen.add(key);const pos=html.indexOf(link.tag);const context=stripTags(html.slice(Math.max(0,pos-180),pos+link.tag.length+180));const role=/(?:создатель|модератор|редактор|переводчик|владелец)/i.exec(context)?.[0]??null;out.push({id:Number.isFinite(id)?id:null,name:link.text,url:link.url,role,scope});}return out;}
export function uniquePeople(values:Person[]):Person[]{const out:Person[]=[];const seen=new Set<string>();for(const v of values){const key=`${v.id??""}:${v.name.toLowerCase()}`;if(seen.has(key))continue;seen.add(key);out.push(v);}return out;}
export function uniqueStrings(values:Array<string|null|undefined>):string[]{const out:string[]=[];const seen=new Set<string>();for(const raw of values){const v=raw?.trim();if(!v)continue;const key=v.toLowerCase();if(seen.has(key))continue;seen.add(key);out.push(v);}return out;}
export function parseInteger(value:string|null|undefined):number|null{if(!value)return null;const normalized=value.replace(/[\s ]/g,"").replace(/[^\d-]/g,"");if(!normalized||normalized==="-")return null;const result=Number(normalized);return Number.isFinite(result)?result:null;}
export function parseRating(value:string|null|undefined):RatingValue{if(!value)return{value:null,percent:null,votes:0};const percentMatch=/(\d+(?:[.,]\d+)?)\s*%\s*\((\d+)\)/.exec(value);if(percentMatch){const percent=Number((percentMatch[1]??"").replace(",","."));return{value:Number.isFinite(percent)?percent/20:null,percent:Number.isFinite(percent)?percent:null,votes:Number(percentMatch[2]??0)};}const slash=/(\d+(?:[.,]\d+)?)\s*\/\s*(\d+)/.exec(value);if(slash)return{value:Number((slash[1]??"").replace(",",".")),percent:null,votes:Number(slash[2]??0)};const numeric=Number(value.replace(",",".").replace(/[^\d.]/g,""));return{value:Number.isFinite(numeric)?numeric:null,percent:null,votes:0};}
export function escapeRegExp(value:string):string{return value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");}
function firstSrcset(value:string|undefined):string|null{return value?.split(",")[0]?.trim().split(/\s+/)[0]??null;}
function escapeAttribute(value:string):string{return value.replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/`/g,"&#96;");}
